import {chromium} from '@playwright/test';
import {mkdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
await mkdir('test-results',{recursive:true});
const browser=await chromium.connectOverCDP('http://127.0.0.1:9242');
const context=browser.contexts()[0];const page=context.pages()[0]||await context.newPage();
await page.goto(process.env.UI_URL||'http://127.0.0.1:4311/');
await page.getByRole('heading',{name:'A clearer view of every learner.'}).waitFor();
await page.waitForFunction(()=>document.fonts.status==='loaded');
await page.screenshot({path:'test-results/meridian-desktop.png',fullPage:true});
console.log((await page.locator('body').innerText()).slice(0,2500));
await page.getByRole('button',{name:'Students 20',exact:true}).click();
await page.getByRole('heading',{name:'A closer look at each student.'}).waitFor();
assert.equal(await page.locator('tbody tr').count(),20);
await page.getByRole('textbox',{name:'Search students'}).fill('Student 16');
assert.equal(await page.locator('tbody tr').count(),1);
await page.getByRole('button',{name:'Explore Synthetic Student 16'}).click();
assert.equal(await page.locator('#student-scope').inputValue(),'STU_016');
await page.getByRole('button',{name:'New conversation'}).click();
await page.getByRole('button',{name:/Grade 8 cohort 7 students/}).click();
assert.equal(await page.locator('#class-scope').inputValue(),'CLASS_08');
await page.getByRole('button',{name:/Make the next lesson count/}).click();
assert.match(await page.getByRole('textbox',{name:'Ask about your students'}).inputValue(),/Grade 8/);
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'test-results/meridian-mobile.png',fullPage:true});
const widths=await page.evaluate(()=>({client:innerWidth,scroll:document.documentElement.scrollWidth}));assert.equal(widths.client,widths.scroll);
await page.getByRole('button',{name:'Open navigation'}).click();
await page.getByRole('button',{name:'Students 20',exact:true}).click();
await page.getByRole('heading',{name:'A closer look at each student.'}).waitFor();
console.log('Passed desktop navigation, live roster, context selection, prompt selection, mobile navigation, and viewport checks.');
await page.setViewportSize({width:1500,height:1000});await browser.close();
