import React,{useEffect,useRef,useState} from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import {ArrowUp,ArrowUpRight,BookOpen,Check,ChevronDown,ChevronRight,Copy,Database,FileText,GraduationCap,Layers,LoaderCircle,MessageSquare,Network,Plus,Search,Square,Users,X,Menu,ArrowLeft,RefreshCw,Trash2} from 'lucide-react';

const api=async(url,options)=>{const response=await fetch(url,options);const data=await response.json();if(!response.ok)throw Error(data.error||'Request failed');return data;};
const stages=['understand','retrieve','traverse','context','generate','verify'];
const percent=(a,b)=>b?Math.round(a/b*100)+'%':'—';
function Mark({small=false}){return <span className={'mark '+(small?'small':'')} aria-hidden="true"><svg viewBox="0 0 28 28"><path d="M5 21V7l9 10 9-10v14M5 7l9 14L23 7"/></svg></span>;}
const cleanTitle=title=>title.length>43?title.slice(0,43)+'…':title;

export default function App(){
  const [data,setData]=useState(null),[health,setHealth]=useState(null),[loadError,setLoadError]=useState('');
  const [view,setView]=useState('chat'),[scope,setScope]=useState({classId:'',studentId:''}),[conversations,setConversations]=useState([]);
  const [conversationId,setConversationId]=useState(null),[messages,setMessages]=useState([]),[draft,setDraft]=useState(''),[pending,setPending]=useState(false);
  const [progress,setProgress]=useState({}),[elapsed,setElapsed]=useState(0),[inspected,setInspected]=useState(null),[inspectTab,setInspectTab]=useState('evidence'),[activeEvidence,setActiveEvidence]=useState(null);
  const [deleteTarget,setDeleteTarget]=useState(null),[deleting,setDeleting]=useState(false),[conversationError,setConversationError]=useState('');
  const [rosterSearch,setRosterSearch]=useState(''),[sidebarOpen,setSidebarOpen]=useState(false),[copied,setCopied]=useState(null);
  const deletedIds=useRef(new Set());
  const acceptConversations=items=>setConversations(items.filter(c=>!deletedIds.current.has(c.id)));
  const abortRef=useRef(null),textRef=useRef(null),bottomRef=useRef(null),draftRef=useRef(null),requestRef=useRef(0);
  const refresh=async()=>{setLoadError('');try{const [loaded,status]=await Promise.all([api('/api/bootstrap'),api('/api/health')]);setData(loaded);acceptConversations(loaded.conversations);setHealth(status);}catch(error){setLoadError(error.message);}};
  useEffect(()=>{refresh();const timer=setInterval(()=>api('/api/health').then(setHealth).catch(()=>setHealth({graph:false,model:{available:false}})),30000);return()=>{clearInterval(timer);abortRef.current?.abort();};},[]);
  useEffect(()=>{if(!pending)return;setElapsed(0);const start=Date.now(),timer=setInterval(()=>setElapsed(Math.floor((Date.now()-start)/1000)),1000);return()=>clearInterval(timer);},[pending]);
  useEffect(()=>{bottomRef.current?.scrollIntoView({behavior:'smooth',block:'end'});},[messages.length,progress.generate?.status]);
  useEffect(()=>{if(activeEvidence)document.getElementById('source-'+activeEvidence)?.scrollIntoView({behavior:'smooth',block:'nearest'});},[activeEvidence,inspected]);
  const cancel=()=>{abortRef.current?.abort();};
  const fresh=(nextScope=scope)=>{setDeleteTarget(null);requestRef.current++;cancel();setPending(false);setScope(nextScope);setConversationId(null);setMessages([]);setProgress({});setInspected(null);setDraft('');setView('chat');setSidebarOpen(false);};
  const loadConversation=async(id)=>{const request=++requestRef.current;cancel();setPending(false);try{const c=await api('/api/conversations/'+id);if(request!==requestRef.current||deletedIds.current.has(id))return;setConversationId(c.id);setScope(c.scope);setMessages(c.messages);setView('chat');setInspected(null);setSidebarOpen(false);}catch(error){setLoadError(error.message);}};
  const inspect=(message,evidenceId)=>{setInspected(message);setInspectTab('evidence');setActiveEvidence(evidenceId||null);};
  async function submit(value){
    const question=(value||draft).trim();if(!question||pending)return;
    const request=++requestRef.current,controller=new AbortController();abortRef.current=controller;
    setView('chat');setPending(true);setProgress({});setDraft('');setInspected(null);
    const user={id:crypto.randomUUID(),role:'user',content:question},assistantId=crypto.randomUUID();
    let assistant={id:assistantId,role:'assistant',content:'',status:'streaming',evidence:[],trace:[]};
    setMessages(current=>[...current,user,assistant]);
    const update=()=>{if(request===requestRef.current)setMessages(current=>current.map(m=>m.id===assistantId?{...assistant}:m));};
    try{
      const response=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question,scope,conversationId}),signal:controller.signal});
      if(!response.ok)throw Error((await response.json()).error);
      const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='';
      while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});let boundary;
        while((boundary=buffer.indexOf('\n\n'))>=0){const block=buffer.slice(0,boundary);buffer=buffer.slice(boundary+2);const line=block.split('\n').find(line=>line.startsWith('data: '));if(!line)continue;const event=JSON.parse(line.slice(6));if(request!==requestRef.current)return;
          if(event.type==='conversation'){setConversationId(event.id);api('/api/conversations').then(acceptConversations).catch(()=>{});}
          if(event.type==='stage')setProgress(current=>({...current,[event.stage.id]:event.stage}));
          if(event.type==='plan')assistant.plan=event.plan;
          if(event.type==='query')assistant.trace=[...assistant.trace,event.query];
          if(event.type==='evidence'){assistant.evidence=event.evidence;assistant.trace=event.trace;assistant.context=event.context;update();}
          if(event.type==='token'){assistant.content+=event.text;update();}
          if(event.type==='done'){assistant={...event.message,id:assistantId};update();}
          if(event.type==='error'){assistant={...assistant,content:event.message,status:'error'};update();}
        }
      }
      if(assistant.status==='streaming'){assistant={...assistant,status:'error',content:'The connection ended before a complete answer was received. Please retry.'};update();}
    }catch(error){assistant={...assistant,content:error.name==='AbortError'?'Generation stopped. Ask again when you’re ready.':error.message,status:error.name==='AbortError'?'canceled':'error'};update();}
    finally{if(request===requestRef.current){setPending(false);api('/api/conversations').then(acceptConversations).catch(()=>{});}}
  }
  async function removeConversation(id){
    setDeleting(true);setConversationError('');
    try{
      await api('/api/conversations/'+id,{method:'DELETE'});
      deletedIds.current.add(id);
      if(id===conversationId)fresh();
      setConversations(current=>current.filter(c=>c.id!==id));setDeleteTarget(null);
      const remaining=await api('/api/conversations');acceptConversations(remaining);
    }catch(error){setConversationError(error.message);}finally{setDeleting(false);}
  }
  async function copy(message){try{await navigator.clipboard.writeText(message.content);setCopied(message.id);setTimeout(()=>setCopied(null),2000);}catch{setCopied('failed');}}
  const selectedClass=data?.classes.find(c=>c.id===scope.classId),selectedStudent=data?.students.find(s=>s.id===scope.studentId);
  const resolved=messages.findLast(m=>m.plan)?.plan;
  const resolvedNames=resolved?[...resolved.student_ids.map(id=>data?.students.find(s=>s.id===id)?.name),...resolved.class_ids.map(id=>data?.classes.find(c=>c.id===id)?.name)].filter(Boolean):[];
  const scopeLabel=resolved?(resolvedNames.join(', ')||'All classes'):selectedStudent?.name||selectedClass?.name||'All classes';
  const visibleStudents=(data?.roster||[]).filter(s=>(!scope.classId||s.class_id===scope.classId)&&(!rosterSearch||(s.name+' '+s.student_id).toLowerCase().includes(rosterSearch.toLowerCase())));
  const suggestions=[
    {icon:Users,label:'CLASS OVERVIEW',title:'How is my class doing?',text:scope.classId?`Give me an overview of ${selectedClass?.name}. Where would a quick check-in help?`:'Give me an overview of my classes. Where would a quick check-in help?'},
    {icon:Network,label:'CONNECT THE DOTS',title:'Look beneath the answer.',text:'Which prerequisites should I investigate for Student 01 when solving linear equations?'},
    {icon:BookOpen,label:'PLAN WHAT’S NEXT',title:'Make the next lesson count.',text:scope.classId?`What should I revisit with ${selectedClass?.name} before teaching slope?`:'What should I revisit with the Grade 8 cohort before teaching slope?'}
  ];
  const currentStage=stages.map(id=>progress[id]).filter(Boolean).at(-1);
  return <div className={'app '+(inspected?'inspecting':'')}>
    {sidebarOpen&&<button className="mobile-scrim" aria-label="Close navigation" onClick={()=>setSidebarOpen(false)}/>}
    <aside className={'sidebar '+(sidebarOpen?'open':'')}>
      <button className="brand" onClick={()=>fresh({classId:'',studentId:''})}><Mark/><span>meridian<span className="brand-sub">A clearer path forward</span></span></button>
      <button className="new-chat" onClick={()=>fresh()}><Plus size={16}/>New conversation<span>↗</span></button>
      <div className="nav-label">WORKSPACE</div>
      <nav aria-label="Main navigation"><button className={view==='chat'?'active':''} onClick={()=>{setView('chat');setSidebarOpen(false);}}><MessageSquare size={17}/>Ask Meridian</button><button className={view==='students'?'active':''} onClick={()=>{setView('students');setInspected(null);setSidebarOpen(false);}}><Users size={17}/>Students<span className="nav-count">{data?.students.length||'—'}</span></button></nav>
      <div className="section-top"><span className="nav-label">YOUR CLASSES</span><span className="tiny-count">{data?.classes.length||0}</span></div>
      <div className="class-list">{data?.classes.map(c=><button key={c.id} className={scope.classId===c.id?'chosen':''} onClick={()=>fresh({classId:c.id,studentId:''})}><span className={'class-symbol grade-'+c.grade}>{c.grade}</span><span>{c.name}<small>{c.students} students</small></span><ChevronRight size={13}/></button>)}</div>
      <div className="section-top recent-label"><span className="nav-label">RECENT CONVERSATIONS</span></div>
      <div className="history">{conversations.length?conversations.map(c=><div className="history-row" key={c.id}>
        <button data-conversation-id={c.id} className={c.id===conversationId?'selected':''} onClick={()=>loadConversation(c.id)} title={c.title}><MessageSquare size={13}/><span>{cleanTitle(c.title)}</span></button>
        <button className="delete-conversation" aria-label={'Delete conversation: '+c.title} title="Delete conversation" onClick={()=>{setDeleteTarget(c.id);setConversationError('');}}><Trash2 size={13}/></button>
        {deleteTarget===c.id&&<div className="delete-confirm" role="group" aria-label="Confirm conversation deletion"><span>Delete this conversation?</span><button disabled={deleting} onClick={()=>removeConversation(c.id)}>{deleting?'Deleting…':'Delete'}</button><button disabled={deleting} onClick={()=>setDeleteTarget(null)}>Cancel</button></div>}
      </div>):<p>Your conversations will appear here.</p>}{conversationError&&<p className="conversation-error" role="alert">{conversationError}</p>}</div>
      <div className="sidebar-bottom"><div className="local-indicator"><span className={'dot '+(health?.model?.available&&health?.graph?'online':'offline')}/><strong>{health?.model?.available?'Qwen 27B · local':'Model offline'}</strong><span className="local-tag">LOCAL</span></div><p>Connected to your learning graph</p><div className="teacher"><span className="avatar">T</span><span>Teacher workspace<small>Synthetic classroom</small></span></div></div>
    </aside>
    <div className="main-area">
      <header className="topbar"><div className="breadcrumb"><button className="mobile-menu icon-button" aria-label="Open navigation" onClick={()=>setSidebarOpen(true)}><Menu size={19}/></button><span>Workspace</span><ChevronRight size={13}/><strong>{view==='students'?'Students':'Ask Meridian'}</strong></div><div className="topbar-right"><span className="dataset-badge"><span/>Synthetic dataset</span><span className="top-avatar">T</span></div></header>
      {loadError?<div className="load-error"><Database size={24}/><h2>Let’s reconnect.</h2><p>{loadError}</p><button onClick={refresh}><RefreshCw size={15}/>Try again</button></div>:!data?<div className="loading"><LoaderCircle className="spin" size={20}/>Connecting to your learning graph…</div>:view==='students'?<section className="roster-page"><div className="page-eyebrow">YOUR LEARNERS</div><h1>A closer look at each student.</h1><p className="page-intro">Recorded progress, with the context behind it.</p><div className="roster-controls"><div className="search-box"><Search size={16}/><input aria-label="Search students" value={rosterSearch} onChange={e=>setRosterSearch(e.target.value)} placeholder="Search students…"/></div><select aria-label="Filter roster by class" value={scope.classId} onChange={e=>setScope({classId:e.target.value,studentId:''})}><option value="">All classes</option>{data.classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="table-wrap"><table><thead><tr><th>STUDENT</th><th>CLASS</th><th>COMPLETED</th><th>FINAL CORRECT</th><th>WITHOUT SUPPORT</th><th/></tr></thead><tbody>{visibleStudents.map(s=><tr key={s.student_id}><td><button className="student-name" onClick={()=>fresh({classId:s.class_id,studentId:s.student_id})}><span className="student-avatar">{s.student_id.slice(-2)}</span><span>{s.name}<small>{s.student_id}</small></span></button></td><td>{s.class_name}</td><td>{s.completed} problems</td><td>{percent(s.correct,s.completed)}</td><td>{percent(s.unassisted_correct,s.completed)}</td><td><button className="icon-button" aria-label={'Explore '+s.name} onClick={()=>fresh({classId:s.class_id,studentId:s.student_id})}><ArrowUpRight size={17}/></button></td></tr>)}</tbody></table>{!visibleStudents.length&&<p className="empty-roster">No students match that search.</p>}</div><p className="table-note">Without support = correct on the first attempt with no hints. These are recorded outcomes, not mastery estimates.</p></section>:<>
      <main className={'chat-main '+(messages.length?'has-messages':'welcome')}>
        {!messages.length?<div className="welcome-content"><div className="page-eyebrow"><span className="eyebrow-line"/>FROM EVIDENCE TO UNDERSTANDING</div><h1>{selectedStudent?<>Every learner has<br/>a story to understand.</>:<>A clearer view of<br/>every learner.</>}</h1><p className="welcome-intro">Ask about progress, uncover possible gaps, and find a thoughtful next step.<br className="desktop-break"/> Grounded in your students’ work and the mathematics that connects it.</p>
        <div className="stats-strip"><span><strong>{selectedStudent?1:scope.classId?selectedClass?.students:data.stats.students}</strong> students</span><i/><span><strong>{selectedStudent||scope.classId?1:data.classes.length}</strong> {selectedStudent||scope.classId?'class':'classes'}</span><i/><span><strong>{selectedStudent?data.roster.find(s=>s.student_id===selectedStudent.id)?.completed:scope.classId?data.roster.filter(s=>s.class_id===scope.classId).reduce((n,s)=>n+s.completed,0):data.stats.completed}</strong> learning records</span><span className="stats-connection"><span className="dot online"/>Graph connected</span></div>
        <div className="suggestion-heading">A good question is a good place to start.</div><div className="suggestions">{suggestions.map(({icon:Icon,label,title,text})=><button className="suggestion" key={label} onClick={()=>{setDraft(text);draftRef.current?.focus();}}><div className="suggestion-top"><Icon size={19}/><ArrowUpRight size={15}/></div><span>{label}</span><strong>{title}</strong></button>)}</div></div>:<div className="conversation"><div className="conversation-heading"><span><MessageSquare size={14}/>{scopeLabel}</span><span className="conversation-label">EVIDENCE-BASED CONVERSATION</span></div>{messages.map((message,index)=><article key={message.id} className={'message '+message.role}>
          {message.role==='user'?<><div className="message-avatar">T</div><div className="user-content">{message.content}</div></>:<><Mark small/><div className="assistant-body"><div className="assistant-name">Meridian<span>{message.status==='complete'?'Qwen 27B':'LOCAL ASSISTANT'}</span></div>
          {(message.status==='error'||message.status==='canceled')?<div className="answer-error"><p>{message.content}</p>{!pending&&<button onClick={()=>submit(messages[index-1]?.content)}>Try again <ArrowUpRight size={13}/></button>}</div>:<>
          {message.content?<div className="answer-text"><ReactMarkdown remarkPlugins={[remarkGfm]} components={{table:({children})=><div className="answer-table-wrap"><table>{children}</table></div>,a:({href,children})=>href?.startsWith('#evidence-')?<button className="citation" onClick={()=>inspect(message,href.slice(10))}>{children}</button>:<a href={href} target="_blank" rel="noreferrer">{children}</a>}}>{message.content.replace(/\[(E\d+)\]/g,'[$1](#evidence-$1)')}</ReactMarkdown></div>:message.status==='streaming'?<div className="thinking"><LoaderCircle size={15} className="spin"/>{currentStage?.label||'Connecting to your graph…'}</div>:null}
          {message.status==='streaming'&&<div className="pipeline" aria-live="polite"><div className="pipeline-label"><span>{currentStage?.label||'Starting retrieval'}</span><span>{elapsed}s</span></div><div className="pipeline-dots">{stages.map((id,i)=><span key={id} className={progress[id]?.status==='done'?'done':progress[id]?'working':''} title={progress[id]?.label||['Understand','Query','Traverse','Assemble','Generate','Verify'][i]}>{progress[id]?.status==='done'?<Check size={10}/>:i+1}</span>)}</div><small>Reading recorded work and mathematical prerequisites.</small></div>}
          {message.status==='complete'&&<><div className="answer-tools"><button onClick={()=>inspect(message)}><Layers size={14}/>{message.evidence?.length||0} evidence records<ChevronRight size={13}/></button><button className="icon-button" aria-label="Copy answer" onClick={()=>copy(message)}>{copied===message.id?<Check size={15}/>:<Copy size={15}/>}</button><span>{Math.round((message.meta?.durationMs||0)/1000)}s · references checked</span></div>{message.meta?.truncated&&<p className="answer-note">The model reached its response limit. Ask a follow-up to continue.</p>}</>}
          </>}</div></>}
        </article>)}<div ref={bottomRef}/></div>}
      </main>
      <div className={'composer-container '+(messages.length?'in-conversation':'')}><form className="composer" onSubmit={e=>{e.preventDefault();submit();}}><div className="composer-context"><span><GraduationCap size={14}/></span><label className="sr-only" htmlFor="class-scope">Class context</label><select id="class-scope" disabled={pending||!!conversationId} value={scope.classId} onChange={e=>setScope({classId:e.target.value,studentId:''})}><option value="">All classes</option>{data.classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><span className="context-divider"/><label className="sr-only" htmlFor="student-scope">Student context</label><select id="student-scope" disabled={pending||!!conversationId} value={scope.studentId} onChange={e=>setScope({...scope,studentId:e.target.value})}><option value="">All students</option>{data.students.filter(s=>!scope.classId||s.class_ids.includes(scope.classId)).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select>{conversationId&&<span className="locked-context">Conversation context</span>}</div><textarea ref={draftRef} aria-label="Ask about your students" maxLength={2400} value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();submit();}}} placeholder={selectedStudent?`What would you like to understand about ${selectedStudent.name}?`:'What would you like to understand about your students?'} rows={2}/><div className="composer-bottom"><span><Network size={13}/>Connected to student work & prerequisites</span>{pending?<button className="send-button stop" type="button" aria-label="Stop generation" onClick={cancel}><Square size={14}/></button>:<button className="send-button" type="submit" aria-label="Send question" disabled={!draft.trim()||!health?.graph||!health?.model?.available}><ArrowUp size={19}/></button>}</div></form><p className="composer-note">A starting point for your judgment. Check the evidence behind every insight.<span>Enter to send · Shift + Enter for a new line</span></p></div>
      </>}
    </div>
    {inspected&&<aside className="evidence-panel"><div className="evidence-header"><div><span className="page-eyebrow">BEHIND THE ANSWER</span><h2>Follow the evidence.</h2></div><button className="icon-button" aria-label="Close evidence" onClick={()=>setInspected(null)}><X size={19}/></button></div><div className="evidence-tabs"><button className={inspectTab==='evidence'?'active':''} onClick={()=>setInspectTab('evidence')}>Evidence <span>{inspected.evidence?.length}</span></button><button className={inspectTab==='queries'?'active':''} onClick={()=>setInspectTab('queries')}>Graph queries <span>{inspected.trace?.length}</span></button></div><div className="evidence-scroll">{inspectTab==='evidence'?<><p className="evidence-explainer">Retrieved records behind this answer. Qwen explains selected investigations; observed numbers come directly from these records. Ratings are synthetic, on a 1–5 scale.</p>{inspected.evidence?.map(e=><section id={'source-'+e.id} className={'evidence-card '+(activeEvidence===e.id?'highlight':'')} key={e.id}><div className="evidence-card-top"><span>{e.id}</span><small>{e.kind}</small></div><h3>{e.title}</h3><EvidenceData evidence={e}/></section>)}</>:<><p className="evidence-explainer">Actual read-only Cypher executed against Neo4j. The query planner resolves entities; validated templates keep retrieval scoped.</p><details className="plan-detail"><summary>Resolved question</summary><pre>{JSON.stringify(inspected.plan,null,2)}</pre></details>{inspected.context?.model_evidence_ids&&<details className="plan-detail"><summary>Evidence supplied to Qwen</summary><pre>{JSON.stringify(inspected.context,null,2)}</pre></details>}{inspected.trace?.map((q,i)=><section className="query-card" key={i}><h3>{q.name}<span>{q.rowCount} rows · {q.elapsedMs} ms</span></h3><pre>{q.cypher}</pre><details><summary>Parameters</summary><pre>{JSON.stringify(q.parameters,null,2)}</pre></details></section>)}</>}</div><div className="evidence-footer"><Database size={13}/>Live Neo4j retrieval · Local Qwen generation</div></aside>}
  </div>;
}

function EvidenceData({evidence:e}){
  const d=e.data;
  if(e.kind==='ranking')return <><p className="problem-text">{d.rule}</p>{d.rows.map(r=><div className="profile-record" key={r.student_id}><strong>{r.student}</strong><p>{r.correct}/{r.completed} final correct · {r.unassisted_correct}/{r.completed} independent</p><small>{r.mean_attempts} mean attempts · {r.mean_hints} mean hints</small></div>)}</>;
  if(e.kind==='screening')return <><p className="problem-text">{d.concepts_checked} selected prerequisites checked. These records suggest a diagnostic, not a confirmed gap.</p>{d.rows.length?d.rows.map(r=><div className="profile-record" key={r.student_id}><strong>{r.student}</strong>{r.prerequisites.map(p=><p key={p.concept_id}>{p.concept}: {p.correct}/{p.completed} final correct · {p.unassisted_correct}/{p.completed} independent</p>)}</div>):<p className="no-evidence">No flagged prerequisite records in this scope.</p>}</>;
  if(e.kind==='profile')return <><p className="problem-text">{d.rows.length} observed skills · {d.unobserved_count} unobserved concepts</p>{d.rows.map(r=><div className="profile-record" key={r.concept_id}><strong>{r.concept}</strong><p>{r.correct}/{r.completed} final correct · {r.unassisted_correct}/{r.completed} independent</p><small>{r.observation}</small></div>)}</>;
  if(e.kind==='investigation')return <><p className="problem-text">{d.interpretation}</p><p className="record-id">Learners flagged at both concepts: {d.overlap_learners.join(', ')||'None observed'}<br/>Flagged target learners with records at both concepts: {d.paired_learners.length}</p><ol className="path-list">{d.path.concepts.map((name,i)=><li key={i}><span>{d.path.concept_ids[i]}</span>{name}</li>)}</ol><details><summary>Why these connections?</summary>{d.path.rationales.map((r,i)=><p className="rationale" key={i}>{r}</p>)}</details><details><summary>Proposed teaching scaffold</summary><p className="rationale">{d.instructional_scaffold?.provenance||'Suggested diagnostic, not an observed intervention.'}</p><p className="rationale">{d.instructional_scaffold?.look_for}</p><p className="rationale">{d.instructional_scaffold?.if_struggle}</p></details><div className="profile-record"><strong>Prerequisite diagnostic</strong><p>{d.diagnostic.prompt}</p><small>Teacher answer key: {d.diagnostic.expected_answer} · {d.diagnostic.problem_id}</small></div><div className="profile-record"><strong>Target transfer task</strong><p>{d.transfer.prompt}</p><small>Teacher answer key: {d.transfer.expected_answer} · {d.transfer.problem_id}</small></div></>;
  if(e.kind==='path')return <><ol className="path-list">{d.concepts.map((name,i)=><li key={i}><span>{d.concept_ids[i]}</span>{name}</li>)}</ol><details><summary>Why these connections?</summary>{d.rationales.map((r,i)=><p className="rationale" key={i}>{r}</p>)}</details></>;
  if(e.kind==='completion')return <><p className="problem-text">{d.problem}</p><div className="response-box"><span>Response: {d.response}</span><strong className={d.correct?'correct':'incorrect'}>{d.correct?'Correct':'Incorrect'}</strong></div><dl className="evidence-metrics"><div><dt>Attempts</dt><dd>{d.attempts}</dd></div><div><dt>Hints</dt><dd>{d.hints}</dd></div><div><dt>Time</dt><dd>{d.seconds}s</dd></div></dl><p className="record-id">{d.completion_id}</p><Affect data={d}/></>;
  return <>{d.completed===0?<p className="no-evidence">No completed problems recorded for this concept in the selected scope.</p>:<><dl className="evidence-metrics"><div><dt>Correct / done</dt><dd>{d.correct} / {d.completed}</dd></div><div><dt>Mean attempts</dt><dd>{d.mean_attempts}</dd></div><div><dt>Mean hints</dt><dd>{d.mean_hints}</dd></div></dl><p className="unassisted">{d.unassisted_correct} correct on the first attempt without hints · {d.mean_seconds}s mean time</p><Affect data={d}/></>}{d.supports&&<p className="record-id">Upstream of {d.supports.join(', ')}</p>}{e.kind==='overview'&&<p className="record-id">{d.students} students · {d.concepts} concepts · All recorded concepts in this scope</p>}</>;
}
function Affect({data}){return <div className="affect-grid">{['confidence','confusion','determination','frustration'].map(key=><span key={key}>{key}<strong>{data[key]??'—'}</strong></span>)}</div>;}
